// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ExceptionRecord.cs" company="WinAPI.NET">
//   Copyright (c) Marek Dzikiewicz, All Rights Reserved.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

namespace WinApiNet.Diagnostics
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.InteropServices;

    /// <summary>
    /// Describes an exception.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public class ExceptionRecord
    {
        /// <summary>
        /// The reason the exception occurred. This is the code generated by a hardware exception, or the code
        /// specified in the <c>RaiseException</c> function for a software-generated exception.
        /// </summary>
        public uint ExceptionCode;

        /// <summary>
        /// The exception flags.
        /// </summary>
        public uint ExceptionFlags;

        /// <summary>
        /// A pointer to an associated <see cref="ExceptionRecord"/> structure. Exception records can be chained
        /// together to provide additional information when nested exceptions occur.
        /// </summary>
        public ExceptionRecord InnerExceptionRecord;

        /// <summary>
        /// The address where the exception occurred.
        /// </summary>
        [SuppressMessage("Microsoft.Security", "CA2111:PointersShouldNotBeVisible")]
        public IntPtr ExceptionAddress;

        /// <summary>
        /// The number of parameters associated with the exception. This is the number of defined elements in the
        /// <see cref="ExceptionInformation"/> array.
        /// </summary>
        public uint NumberParameters;

        /// <summary>
        /// An array of additional arguments that describe the exception. The <c>RaiseException</c> function can
        /// specify this array of arguments. For most exception codes, the array elements are undefined.
        /// </summary>
        [SuppressMessage("Microsoft.Security", "CA2111:PointersShouldNotBeVisible")]
        public IntPtr ExceptionInformation;
    }
}